// ═══════════════════════════════════════════════════════
// ADMIN CONFIG
// ═══════════════════════════════════════════════════════
export const INIT_CONFIG = {
  expFmt: "",
  billFmt: "",
  advFmt: "",
  invFmt: "",
  advEnabled: true,
  advCap: 0,
  balanceCap: 0,
  ccEmails: ["accounts@qubiqon.io", "finance@qubiqon.io"],
  expSeq: 7,
  billSeq: 206,
  advSeq: 4,
  invSeq: 115,
  org: {
    name: "Qubiqon Consulting India Private Ltd",
    legalName: "Qubiqon Consulting India Private Limited",
    gstin: "32AAACQ9628B1ZP",
    pan: "AAACQ9628B",
    cin: "",
    tan: "",
    addr1: "Carnival building Unit No VI C 6th Floor Phase 3 Building",
    addr2: "Infopark Kochi, Kakkanad",
    city: "Ernakulam",
    state: "Kerala",
    country: "India",
    pin: "682030",
    contactPerson: "Biju Neduvellil",
    contactEmail: "finance@qubiqon.io",
    contactPhone: "",
    website: "https://www.qubiqon.io",
    bankAccName: "QUBIQON CONSULTING INDIA PRIVATE LIMITED",
    bankAccNo: "001005015268",
    bankIfsc: "ICIC0000010",
    bankName: "ICICI Bank Ltd",
    bankBranch: "ICICI Bank Ltd, Emgee Square, M. G. Road, Ernakulam, Kochi",
    bankSwift: "ICICINBBCTS",
    primaryColor: "#1B2A4A",
    accentColor: "#E8593C",
    logoUrl: "",
  },
  taxes: [
    { id: "T01", name: "Commission or Brokerage", rate: 5, section: "194 H", active: true },
    { id: "T02", name: "Commission or Brokerage (Reduced)", rate: 3.75, section: "194 H", active: true },
    { id: "T03", name: "Dividend", rate: 10, section: "194", active: true },
    { id: "T04", name: "Dividend (Reduced)", rate: 7.5, section: "194", active: true },
    { id: "T05", name: "Other Interest than securities", rate: 10, section: "194 A", active: true },
    { id: "T06", name: "Other Interest (Reduced)", rate: 7.5, section: "194 A", active: true },
    { id: "T07", name: "Payment of contractors for Others", rate: 2, section: "194 C", active: true },
    { id: "T08", name: "Payment of contractors (Reduced)", rate: 1.5, section: "194 C", active: true },
    { id: "T09", name: "Payment of contractors HUF/Indiv", rate: 1, section: "194 C", active: true },
    { id: "T10", name: "Payment of contractors HUF (Reduced)", rate: 0.75, section: "194 C", active: true },
    { id: "T11", name: "Professional Fees", rate: 10, section: "194 J", active: true },
    { id: "T12", name: "Professional Fees (Reduced)", rate: 7.5, section: "194 J", active: true },
    { id: "T13", name: "Rent on land or furniture", rate: 10, section: "194 I", active: true },
    { id: "T14", name: "Rent (Reduced)", rate: 7.5, section: "194 I", active: true },
    { id: "T15", name: "Technical Fees (2%)", rate: 2, section: "194 J", active: true },
    { id: "T16", name: "Tent on Machinery", rate: 2, section: "194 I", active: true },
  ],
  gstTypes: [
    { id: "G01", name: "GST @0%", rate: 0, active: true },
    { id: "G02", name: "GST @5%", rate: 5, active: true },
    { id: "G03", name: "GST @12%", rate: 12, active: true },
    { id: "G04", name: "GST @18%", rate: 18, active: true },
    { id: "G05", name: "GST @28%", rate: 28, active: true },
    { id: "G06", name: "IGST @0%", rate: 0, type: "IGST", active: true },
    { id: "G07", name: "IGST @5%", rate: 5, type: "IGST", active: true },
    { id: "G08", name: "IGST @12%", rate: 12, type: "IGST", active: true },
    { id: "G09", name: "IGST @18%", rate: 18, type: "IGST", active: true },
    { id: "G10", name: "IGST @28%", rate: 28, type: "IGST", active: true },
    { id: "G11", name: "Exempt", rate: 0, active: true },
    { id: "G12", name: "Zero Rated (SEZ/Export)", rate: 0, type: "SEZ", active: true },
  ],
} as const;
